version: '3.1'
 
services:
  db-content:
    image: mariadb
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=intensive --password=intensive --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - "3308:3306"
    container_name : db-content
    environment:
      - MYSQL_ROOT_PASSWORD=nexcore
      - MYSQL_DATABASE=intensive
      - MYSQL_USER=intensive
      - MYSQL_PASSWORD=intensive
      - TZ=Asia/Seoul
    volumes:
      - /apps/intensive/content/mariadb/data:/var/lib/mysql
      - /apps/intensive/content/mariadb/conf.d:/etc/mysql/conf.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  intensive-content:
    image: iij57/intensive-content:1.0
    restart: always
    container_name : intensive-content
    environment:
      - MYSQL_URL=db-content
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=intensive
      - MYSQL_USER=intensive
      - MYSQL_PASSWORD=intensive
      - TZ=Asia/Seoul
    ports:
      - "8082:8080"
    depends_on:
      - db-content